#!/bin/bash
# ============================================================================
# Skilldex IT Deployment Script
# ============================================================================
# Deploys Skilldex client components to recruiter workstations.
# Run with sudo for system-wide installation.
#
# Usage:
#   sudo ./skilldex-deploy.sh --api-url https://skilldex.company.com
#   sudo ./skilldex-deploy.sh --api-url https://skilldex.company.com --user jsmith
#
# Options:
#   --api-url URL       Skilldex API URL (required)
#   --user USERNAME     Deploy for specific user (default: console user)
#   --help              Show this help message
#
# ============================================================================

set -e

VERSION="2.0.0"

# ============================================================================
# Configuration
# ============================================================================

SKILLDEX_API_URL=""
USER_HOME=""
CURRENT_USER=""
VERBOSE="false"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

show_help() {
  head -20 "$0" | tail -15
  exit 0
}

check_root() {
  if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run with sudo"
    exit 1
  fi
}

detect_os() {
  case "$(uname -s)" in
    Darwin*)  echo "macos" ;;
    Linux*)   echo "linux" ;;
    MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
    *)        echo "unknown" ;;
  esac
}

# ============================================================================
# Parse Arguments
# ============================================================================

while [[ $# -gt 0 ]]; do
  case $1 in
    --api-url)
      SKILLDEX_API_URL="$2"
      shift 2
      ;;
    --user)
      CURRENT_USER="$2"
      shift 2
      ;;
    --verbose|-v)
      VERBOSE="true"
      shift
      ;;
    --help|-h)
      show_help
      ;;
    *)
      log_error "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

# ============================================================================
# Validation
# ============================================================================

if [ -z "$SKILLDEX_API_URL" ]; then
  log_error "--api-url is required"
  echo "Example: sudo ./skilldex-deploy.sh --api-url https://skilldex.company.com"
  exit 1
fi

OS=$(detect_os)
if [ "$OS" = "unknown" ]; then
  log_error "Unsupported operating system"
  exit 1
fi

# Detect current user
if [ -z "$CURRENT_USER" ]; then
  if [ "$OS" = "macos" ]; then
    CURRENT_USER=$(stat -f "%Su" /dev/console 2>/dev/null || echo "$SUDO_USER")
  else
    CURRENT_USER="$SUDO_USER"
  fi
fi

if [ -z "$CURRENT_USER" ] || [ "$CURRENT_USER" = "root" ]; then
  log_error "Could not detect user. Use --user to specify."
  exit 1
fi

USER_HOME=$(eval echo "~$CURRENT_USER")

# ============================================================================
# Display Configuration
# ============================================================================

echo ""
echo "============================================"
echo "  Skilldex IT Deployment Script v$VERSION"
echo "============================================"
echo ""
echo "  Configuration:"
echo "    API URL:      $SKILLDEX_API_URL"
echo "    User:         $CURRENT_USER"
echo "    Home:         $USER_HOME"
echo "    OS:           $OS"
echo ""
echo "============================================"
echo ""

# ============================================================================
# Step 1: Create Directories
# ============================================================================

log_info "[1/4] Creating directories..."

sudo -u "$CURRENT_USER" mkdir -p "$USER_HOME/.skilldex"
sudo -u "$CURRENT_USER" mkdir -p "$USER_HOME/.claude/commands"

# ============================================================================
# Step 2: Create Skilldex Configuration
# ============================================================================

log_info "[2/4] Creating Skilldex configuration..."

# Create config file
cat > "$USER_HOME/.skilldex/config.json" << EOF
{
  "apiUrl": "$SKILLDEX_API_URL",
  "installed": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "version": "$VERSION"
}
EOF
chown "$CURRENT_USER" "$USER_HOME/.skilldex/config.json"

# Create shell initialization script
cat > "$USER_HOME/.skilldex/shell-init.sh" << EOF
# Skilldex environment configuration
# Generated by skilldex-deploy.sh on $(date)

export SKILLDEX_API_URL="$SKILLDEX_API_URL"

# Load API key from Keychain (macOS) or secret-tool (Linux)
if [ "\$(uname)" = "Darwin" ]; then
  _skilldex_key=\$(security find-generic-password -a "\$USER" -s "SKILLDEX_API_KEY" -w 2>/dev/null)
elif command -v secret-tool &> /dev/null; then
  _skilldex_key=\$(secret-tool lookup service skilldex username "\$USER" 2>/dev/null)
fi

if [ -n "\$_skilldex_key" ]; then
  export SKILLDEX_API_KEY="\$_skilldex_key"
fi
unset _skilldex_key
EOF
chown "$CURRENT_USER" "$USER_HOME/.skilldex/shell-init.sh"

# Add to shell profiles
for profile in "$USER_HOME/.zshrc" "$USER_HOME/.bashrc" "$USER_HOME/.bash_profile"; do
  if [ -f "$profile" ] || [ "$profile" = "$USER_HOME/.zshrc" ]; then
    if ! grep -q "skilldex/shell-init.sh" "$profile" 2>/dev/null; then
      echo "" >> "$profile"
      echo "# Skilldex" >> "$profile"
      echo "[ -f ~/.skilldex/shell-init.sh ] && source ~/.skilldex/shell-init.sh" >> "$profile"
      chown "$CURRENT_USER" "$profile"
    fi
  fi
done

# ============================================================================
# Step 3: Install Health Check Skill
# ============================================================================

log_info "[3/4] Installing health check skill..."

SKILLS_DIR="$USER_HOME/.claude/commands"

# Create health check skill
cat > "$SKILLS_DIR/skilldex-health-check.md" << 'SKILLEOF'
---
name: skilldex-health-check
description: Verify your Skilldex installation is working correctly
intent: I want to check if Skilldex is set up correctly
capabilities:
  - Check API key configuration
  - Test API connectivity
allowed-tools:
  - Bash
  - Read
---

# Skilldex Health Check

Run these checks to verify your installation:

## 1. Environment Check

```bash
echo "=== Skilldex Health Check ==="
echo ""

# Check API URL
if [ -n "$SKILLDEX_API_URL" ]; then
  echo "✓ API URL: $SKILLDEX_API_URL"
else
  echo "✗ SKILLDEX_API_URL not set"
fi

# Check API key
if [ -n "$SKILLDEX_API_KEY" ]; then
  echo "✓ API key is configured (${SKILLDEX_API_KEY:0:10}...)"
else
  echo "✗ SKILLDEX_API_KEY not set"
  echo "  To fix: security add-generic-password -a $USER -s SKILLDEX_API_KEY -w 'your-key'"
fi
```

## 2. API Connectivity

```bash
if [ -n "$SKILLDEX_API_KEY" ]; then
  response=$(curl -s -w "\n%{http_code}" \
    -H "Authorization: Bearer $SKILLDEX_API_KEY" \
    "$SKILLDEX_API_URL/api/v1/me")

  http_code=$(echo "$response" | tail -1)
  body=$(echo "$response" | head -n -1)

  if [ "$http_code" = "200" ]; then
    echo "✓ API connection successful"
    echo "  User: $(echo $body | grep -o '"email":"[^"]*"' | cut -d'"' -f4)"
  else
    echo "✗ API connection failed (HTTP $http_code)"
  fi
else
  echo "⊘ Skipping API check (no API key)"
fi
```

## 3. Skills Check

```bash
echo ""
echo "=== Installed Skills ==="
ls -la ~/.claude/commands/
```

## Summary

If any checks failed, contact IT support with the output above.
SKILLEOF

chown -R "$CURRENT_USER" "$SKILLS_DIR"

# ============================================================================
# Step 4: Summary
# ============================================================================

log_info "[4/4] Deployment complete!"

echo ""
echo "============================================"
echo "  Deployment Complete!"
echo "============================================"
echo ""
echo "  Installed components:"
echo "    ✓ Skilldex config: ~/.skilldex/"
echo "    ✓ Shell initialization: ~/.skilldex/shell-init.sh"
echo "    ✓ Health check skill: ~/.claude/commands/"
echo ""
echo "  Next steps for the user:"
echo "    1. Log in to $SKILLDEX_API_URL"
echo "    2. Generate an API key from the dashboard"
echo "    3. Store it securely:"

if [ "$OS" = "macos" ]; then
  echo "       security add-generic-password -a \$USER -s SKILLDEX_API_KEY -w 'sk_live_xxx'"
elif [ "$OS" = "linux" ]; then
  echo "       secret-tool store --label='Skilldex API Key' service skilldex username \$USER"
fi

echo "    4. Download skills from the Skilldex web UI"
echo "    5. Move skills to ~/.claude/commands/"
echo "    6. Restart terminal"
echo ""
echo "  Verify installation:"
echo "    Type /skilldex-health-check in Claude"
echo ""
echo "============================================"
