/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    JwtSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    NangoSecretKey: {
      type: "sst.sst.Secret";
      value: string;
    };
    NangoPublicKey: {
      type: "sst.sst.Secret";
      value: string;
    };
    TursoAuthToken: {
      type: "sst.sst.Secret";
      value: string;
    };
    TursoDatabaseUrl: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
  }
}

export {};
